name: Build PlatformIO project
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: cache platformio
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/platformio.ini') }}
          path: |
            ~/.platformio
            .pio/libdeps

      - name: Setup PlatformIO
        uses: n-vr/setup-platformio-action@v1
      
      - name: Build PlatformIO project
        run: pio run

      - name: save built image
        uses: actions/upload-artifact@v3
        with:
          name: zumambe_firmware.${{ github.sha }}.bin
          path: .pio/build/lolin32/firmware.bin
          if-no-files-found: error
          retention-days: 10
